/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_dianahep_jaroot_TFileWrapper */

#ifndef _Included_org_dianahep_jaroot_TFileWrapper
#define _Included_org_dianahep_jaroot_TFileWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_dianahep_jaroot_TFileWrapper
 * Method:    new_TFile
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_dianahep_jaroot_TFileWrapper_new_1TFile
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_dianahep_jaroot_TFileWrapper
 * Method:    delete_TFile
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_dianahep_jaroot_TFileWrapper_delete_1TFile
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_dianahep_jaroot_TFileWrapper
 * Method:    TFile_ls
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_dianahep_jaroot_TFileWrapper_TFile_1ls
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
